//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuotThuMua
    {
        public int Id { get; set; }
        public int IdChuVuon { get; set; }
        public int IdNhaXe { get; set; }
        public double SoLuong { get; set; }
        public int DonGia { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public int TongTien { get; set; }
        public double HamLuong { get; set; }
        public bool IsMuMuoc { get; set; }
    
        public virtual ChuVuon ChuVuon { get; set; }
        public virtual NhaXe NhaXe { get; set; }
    }
}
